#!/bin/bash

proxyPort=$1
proxyAddress=http://localhost:$proxyPort

function log {
	echo "# $@"
}

log "Starting chromium with proxy: $proxyAddress..."

chromium-browser --proxy-server=$proxyAddress

