#!/bin/bash

pushd app

function log {
	echo "# $@"
}

localPort=$1
configFile=$2
log "Running WSMocker on port: $localPort with config file: $configFile"

grails -Dserver.port=$localPort -Dwsmocker.config=$configFile run-app

