#!/bin/bash

pushd app

function log {
	echo "# $@"
}

localPort=$1
configFile=$2
log "Running WSMocker on port: $localPort with config file: $configFile"

grails run-app -Dserver.port=$localPort -Duse.root.context.path=true -Dwsmocker.config=$configFile

