#!/bin/bash
source lib/util

pushd app

localPort=$1
configFile=$2
httpsPort=$3
log "Running WSMocker on port: $localPort, https port: $httpsPort;  with config file: $configFile"

httpsOption=''
if [[ -n $httpsPort ]]; then
	httpsOption="-https -Dgrails.server.port.https=$httpsPort"
fi
grailsCommand="grails -Dserver.port=$localPort $httpsOption -Dwsmocker.config=$configFile run-app"
log "Executing grails command:"
log "    $grailsCommand"
$grailsCommand

